services:
  database:
    image: postgres:latest
    container_name: backend-database
    ports:
        - "5432:5432"
    environment:
        POSTGRES_USER: root
        POSTGRES_PASSWORD: root
        POSTGRES_DB: backend
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: backend:latest
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/backend
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_SERVER_PORT: 9090
    depends_on:
      - database

volumes:
  pg_data:
