

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/backend}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
    driver-class-name: org.postgresql.Driver
# Optional: Define the JPA properties
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

# Optional: Define the logging level for SQL queries
  logging:
    level:
      org:
        hibernate:
          SQL: debug
          type:
            descriptor:
              sql:
                BasicBinder: trace

#  Optional: Enable GraphiQL interface for
  graphql:
    graphiql:
      enabled: true
    schema:
      locations: classpath*:graphql/**
server:
  port: ${SPRING_SERVER_PORT:8081}
